Pin connection_pool version
Dependencies of this gem are getting

```
ArgumentError: unknown keyword: :name
```

This seems to be related to mperham/connection_pool#210

We will pin the version until a backport to v7 is available, or an upgrade to v8 is complete, or a rails fix is released:

https://gov-uk.atlassian.net/browse/PP-7021?atlOrigin=eyJpIjoiMjAyMWMwMTQxYzlhNGQ5YTk5NDVkNTJlYjQ4MGJhN2EiLCJwIjoiaiJ

https://github.com/rails/rails/pull/56292