GovukLogging is required before Railtie
This ordering was causing a problem for govuk_publishing_components which prevented assets to be pre-compiled:

```
govuk_publishing_components git:(master) RAILS_ENV=production GOVUK_APP_DOMAIN=www.gov.uk GOVUK_WEBSITE_ROOT=https://www.gov.uk rake assets:precompile
rake aborted!
NameError: uninitialized constant GovukAppConfig::Railtie::GovukLogging
/Users/kevindew/govuk/govuk_publishing_components/spec/dummy/config/initializers/content_security_policy.rb:1:in `<top (required)>'
/Users/kevindew/govuk/govuk_publishing_components/spec/dummy/config/environment.rb:5:in `<top (required)>'
/Users/kevindew/govuk/govuk_publishing_components/Rakefile:18:in `block (2 levels) in <top (required)>'
```

This was due to the Railtie file executing it's initializer before the remaining files had been required. This can be resolved with the Railtie being required last.